Test Publish workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -17,115 +17,122 @@ jobs:
         platform:
           - linux/amd64
           - linux/arm64
-        use_bedrock:
-          - true
-          - false
+        flavor:
+          - name: slim
+            build_args: []
+          - name: full
+            build_args: ["USE_BEDROCK=true"]
     steps:
-      - name: Prepare
+      - name: Echo matrix values
         run: |
-          platform=${{ matrix.platform }}
-          suffix=$([[ "${{ matrix.use_bedrock }}" == "true" ]] && echo "-bedrock" || echo "")
-          echo "DIGEST_NAME=digests-${platform//\//-}${suffix}" >> $GITHUB_ENV
-
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY_IMAGE }}
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build and push by digest
-        id: build
-        uses: docker/build-push-action@v6
-        with:
-          platforms: ${{ matrix.platform }}
-          labels: ${{ steps.meta.outputs.labels }}
-          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
-
-      - name: Export digest
-        run: |
-          mkdir -p /tmp/digests
-          digest="${{ steps.build.outputs.digest }}"
-          touch "/tmp/digests/${digest#sha256:}"
-
-      - name: Upload digest
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.DIGEST_NAME }}
-          path: /tmp/digests/*
-          if-no-files-found: error
-          retention-days: 1
-
-  merge:
-    runs-on: ubuntu-latest
-    permissions:
-      packages: write
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        use_bedrock:
-          - true
-          - false
-    steps:
-      - name: Prepare
-        run: |
-          suffix=$([[ "${{ matrix.use_bedrock }}" == "true" ]] && echo "-bedrock" || echo "")
-          echo "DIGEST_SUFFIX=${suffix}" >> $GITHUB_ENV
-
-      - name: Download digests
-        uses: actions/download-artifact@v4
-        with:
-          path: /tmp/digests
-          pattern: digests-*${{ env.DIGEST_SUFFIX }}
-          merge-multiple: true
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY_IMAGE }}
-          tags: |
-            type=schedule
-            type=ref,event=branch
-            type=ref,event=tag
-            type=ref,event=pr
-            type=semver,pattern={{version}}
-
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Create manifest list and push
-        working-directory: /tmp/digests
-        run: |
-          suffix=$([[ "${{ matrix.use_bedrock }}" == "true" ]] && echo "-bedrock" || echo "")
-          tags=$(jq -cr --arg suffix "$suffix" '.tags | map("-t " + . + $suffix) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
-          docker buildx imagetools create $tags \
-            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
-
-      - name: Inspect image
-        run: |
-          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
+          echo "Platform: ${{ matrix.platform }}"
+          echo "Flavor Name: ${{ matrix.flavor.name }}"
+          echo "Build Args: ${{ join(matrix.flavor.build_args, ' ') }}"
+#      - name: Prepare
+#        run: |
+#          platform=${{ matrix.platform }}
+#          suffix=$([[ "${{ matrix.use_bedrock }}" == "true" ]] && echo "-bedrock" || echo "")
+#          echo "DIGEST_NAME=digests-${platform//\//-}${suffix}" >> $GITHUB_ENV
+#
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Docker meta
+#        id: meta
+#        uses: docker/metadata-action@v5
+#        with:
+#          images: ${{ env.REGISTRY_IMAGE }}
+#
+#      - name: Set up QEMU
+#        uses: docker/setup-qemu-action@v3
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#
+#      - name: Login to GitHub Container Registry
+#        uses: docker/login-action@v3
+#        with:
+#          registry: ghcr.io
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Build and push by digest
+#        id: build
+#        uses: docker/build-push-action@v6
+#        with:
+#          platforms: ${{ matrix.platform }}
+#          labels: ${{ steps.meta.outputs.labels }}
+#          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
+#
+#      - name: Export digest
+#        run: |
+#          mkdir -p /tmp/digests
+#          digest="${{ steps.build.outputs.digest }}"
+#          touch "/tmp/digests/${digest#sha256:}"
+#
+#      - name: Upload digest
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: ${{ env.DIGEST_NAME }}
+#          path: /tmp/digests/*
+#          if-no-files-found: error
+#          retention-days: 1
+#
+#  merge:
+#    runs-on: ubuntu-latest
+#    permissions:
+#      packages: write
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        use_bedrock:
+#          - true
+#          - false
+#    steps:
+#      - name: Prepare
+#        run: |
+#          suffix=$([[ "${{ matrix.use_bedrock }}" == "true" ]] && echo "-bedrock" || echo "")
+#          echo "DIGEST_SUFFIX=${suffix}" >> $GITHUB_ENV
+#
+#      - name: Download digests
+#        uses: actions/download-artifact@v4
+#        with:
+#          path: /tmp/digests
+#          pattern: digests-*${{ env.DIGEST_SUFFIX }}
+#          merge-multiple: true
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3
+#
+#      - name: Docker meta
+#        id: meta
+#        uses: docker/metadata-action@v5
+#        with:
+#          images: ${{ env.REGISTRY_IMAGE }}
+#          tags: |
+#            type=schedule
+#            type=ref,event=branch
+#            type=ref,event=tag
+#            type=ref,event=pr
+#            type=semver,pattern={{version}}
+#
+#      - name: Login to GitHub Container Registry
+#        uses: docker/login-action@v3
+#        with:
+#          registry: ghcr.io
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Create manifest list and push
+#        working-directory: /tmp/digests
+#        run: |
+#          suffix=$([[ "${{ matrix.use_bedrock }}" == "true" ]] && echo "-bedrock" || echo "")
+#          tags=$(jq -cr --arg suffix "$suffix" '.tags | map("-t " + . + $suffix) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
+#          docker buildx imagetools create $tags \
+#            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
+#
+#      - name: Inspect image
+#        run: |
+#          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
